# Generated by Django 5.0.3 on 2024-05-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_department_alter_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateOfJoining',
            field=models.DateField(),
        ),
    ]
